name: Move Joe Theme

on:
  workflow_dispatch: # 手动触发工作流

jobs:
  move-joe:
    runs-on: ubuntu-latest
    steps:
      # 检出目标仓库 (typecho123)
      - name: Checkout typecho123
        uses: actions/checkout@v4
        with:
          repository: aw168/typecho123
          token: ${{ secrets.PAT }}
          ref: master  # 指定目标分支

      # 检出源仓库 (awbk) 的所有文件
      - name: Checkout awbk repository
        uses: actions/checkout@v4
        with:
          repository: aw168/awbk
          path: temp-awbk
          token: ${{ secrets.PAT }}

      # 创建目标目录并移动 Joe 主题文件
      - name: Move Joe files
        run: |
          mkdir -p usr/themes/Joe
          cp -r temp-awbk/usr/themes/Joe/* usr/themes/Joe/  # 仅复制 Joe 文件夹内容
          rm -rf temp-awbk  # 清理临时文件夹

      # 提交更改到 typecho123
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add -f usr/themes/Joe  # 强制添加整个Joe文件夹
          git commit -m "自动移动 Joe 主题文件从 awbk 仓库" || echo "没有新更改"
          git push origin master  # 推送回master分支
