name: Unzip Joe.zip

on:
  push:
    branches:
      - main # 或者您的主要分支名称

jobs:
  unzip_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create target directory
        run: |
          mkdir -p typecho/usr/themes/

      - name: Unzip Joe.zip
        run: |
          unzip Joe.zip -d typecho/usr/themes/

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add typecho/usr/themes/* # 添加解压后的文件
          git commit -m "Auto-unzip Joe.zip to themes directory"
          git push origin ${{ github.ref_name }}
