name: Unzip and Move Files
on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip file
        run: |
          unzip Joe.zip -d usr/themes
        shell: bash
