name: Unzip and Move Files
on: [push]

permissions:
  contents: write  # 允许 GitHub Actions 写入仓库

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List repository files (debugging)
        run: ls -l
        shell: bash

      - name: Create target directory
        run: mkdir -p usr/themes
        shell: bash

      - name: Unzip file
        run: |
          if [ -f "Joe.zip" ]; then
            unzip -o "Joe.zip" -d "usr/themes"
            echo "Unzip completed."
          else
            echo "Joe.zip not found!"
            exit 1
          fi
        shell: bash

      - name: Verify extracted files
        run: |
          echo "Checking usr/themes contents..."
          ls -R usr/themes || echo "No files found in usr/themes!"
        shell: bash

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet || git commit -m "Unzip archive to usr/themes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
