name: Unzip Joe Theme

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip Joe.zip
        run: |
          mkdir -p usr/themes
          unzip -o Joe.zip -d usr/themes/

      - name: List extracted files
        run: ls -la usr/themes/
