name: Unzip and Move Files
on: [push]

permissions:
  contents: write  # Allow write access to the repository

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip file
        run: |
          ls -l  # List files to verify Joe.zip exists
          unzip Joe.zip -d usr/themes
        shell: bash

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet || git commit -m "Unzip archive to usr/themes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
