name: Unzip Joe Theme

on:
  push:
    branches:
      - master
      - 'typecho/usr/themes'  # 确保包含你的当前分支
  workflow_dispatch:  # 允许手动触发

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y unzip
        echo "Environment setup complete"

    - name: Debug and Unzip Joe.zip to usr/themes
      run: |
        echo "Current working directory:"
        pwd
        echo "Listing root directory contents:"
        ls -la
        if [ -f "Joe.zip" ]; then
          echo "Joe.zip found, proceeding with unzip..."
          mkdir -p usr/themes
          unzip -o "Joe.zip" -d usr/themes || { echo "Unzip failed"; exit 1; }
          echo "Unzip completed, listing usr/themes directory:"
          ls -la usr/themes
          if [ -d "usr/themes/Joe" ]; then
            echo "Nested Joe directory found, moving contents..."
            mv "usr/themes/Joe/"* "usr/themes/" 2>/dev/null || echo "No files to move or move failed"
            rmdir "usr/themes/Joe" 2>/dev/null || echo "Failed to remove Joe directory"
            echo "Moved contents, listing usr/themes again:"
            ls -la usr/themes
          fi
        else
          echo "Error: Joe.zip not found in the root directory"
          ls -la
          exit 1
        fi

    - name: Verify extraction
      run: |
        if [ -d "usr/themes" ]; then
          echo "usr/themes directory exists and contains:"
          ls -la usr/themes
          if [ "$(ls -A usr/themes)" ]; then
            echo "Verification successful: usr/themes directory is not empty"
          else
            echo "Error: usr/themes directory is empty"
            exit 1
          fi
        else
          echo "Error: usr/themes directory does not exist"
          exit 1
        fi

    - name: Commit changes
      run: |
        if [ -d "usr/themes" ] && [ "$(ls -A usr/themes)" ]; then
          git config --global user.name "Your Name"
          git config --global user.email "your.email@example.com"
          git add usr/themes
          git commit -m "Add unzipped Joe theme files" || echo "No changes to commit"
          git push
        fi
