name: Move Joe Folder

on:
  workflow_dispatch:

jobs:
  move-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source repository
        run: |
          git clone https://github.com/aw168/awbk.git
          ls awbk/usr/themes/Joe # 确认 Joe 文件夹是否存在
          cp -r awbk/usr/themes/Joe ./Joe

      - name: Checkout destination repository
        uses: actions/checkout@v3
        with:
          repository: aw168/typecho123
          ref: master

      - name: Move Joe folder to destination
        run: |
          mv ./Joe usr/themes

      - name: Commit and push changes
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "YourEmail@example.com"
          git add usr/themes/Joe
          git commit -m "Moved Joe folder from awbk to typecho123"
          git push
