name: Unzip Joe Theme

on: [push, pull_request]

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip

    - name: Debug and Unzip Joe.zip to themes
      run: |
        echo "Checking root directory contents:"
        ls -la
        if [ -f Joe.zip ]; then
          mkdir -p themes
          unzip -o Joe.zip -d themes
          echo "Unzipped contents to themes directory"
          echo "Listing themes directory:"
          ls -la themes
          if [ -d themes/Joe ]; then
            echo "Moving contents from themes/Joe to themes/"
            mv themes/Joe/* themes/ || true
            rmdir themes/Joe || true
            echo "Moved contents, listing themes again:"
            ls -la themes
          fi
        else
          echo "Error: Joe.zip not found in the root directory"
          exit 1
        fi

    - name: Verify extraction
      run: |
        if [ -d themes ]; then
          echo "themes directory exists and contains:"
          ls -la themes
        else
          echo "Error: Failed to create or find themes directory"
          exit 1
        fi
